### ISSUE TITLE
Kullanıcı Giriş, Kayıt

### ISSUE THREAD

**Issue by ilteriskeskin** [ilteriskeskin/django-ecommerce#2]
Kullanıcının sepete ürün ekleme gibi özelliklerden faydalanabilmesi için giriş ve kayıt uygulamalarının yazılması

**Comment by Ksenofanex** [comment]
Authentication'ı ben ekleyebilirim, üzerinde çalışmaya başlıyorum.

**Comment by ilteriskeskin** [comment]
@Ksenofanex tarafından kısa sürede yapıldı :+1:
